import fs from 'fs';
import path from 'path';

const ruPath = path.join(process.cwd(), 'src/i18n/locales/ru/calculators.json');
const kkPath = path.join(process.cwd(), 'src/i18n/locales/kk/calculators.json');
const ruJson = JSON.parse(fs.readFileSync(ruPath, 'utf-8'));
const kkJson = JSON.parse(fs.readFileSync(kkPath, 'utf-8'));

// DISCOUNT
const discountRu = {
  "subtitle": "Расчет скидок и сравнение предложений",
  "addDiscount": "Добавить скидку",
  "addOption": "Добавить вариант",
  "additionalDiscountLabel": "Доп. скидка (%)",
  "afterHolidaySales": "Распродажи после праздников",
  "appliedDiscounts": "Примененные скидки",
  "applyingSteps": "Порядок применения",
  "bestOption": "Лучший вариант",
  "blackFriday": "Черная пятница",
  "calculation": "Расчет",
  "calculationExamples": "Примеры расчетов",
  "calculationFormulas": "Формулы расчета",
  "calculationResult": "Результат расчета",
  "calculationType": "Тип расчета",
  "cascadeDescription": "Последовательное применение нескольких скидок",
  "cascadeDiscounts": "Каскадные скидки",
  "cascadeDiscountsTip": "Каскадные скидки применяются последовательно",
  "cascadeExample": "Пример каскадных скидок",
  "cascadeFeatures": "Особенности каскадных скидок",
  "cascadeFeaturesDesc": "Каждая следующая скидка применяется к уже уменьшенной цене",
  "cascadeResult": "Результат каскадных скидок",
  "cascadeTipDesc": "Общая скидка меньше суммы отдельных",
  "compareDescription": "Сравнение нескольких предложений",
  "compareDiscounts": "Сравнить скидки",
  "compareExample": "Пример сравнения",
  "compareOffersTip": "Сравнивайте финальные цены",
  "compareTipDesc": "Большая скидка не всегда выгоднее",
  "comparisonResults": "Результаты сравнения",
  "coolingDevices": "Кондиционеры и вентиляторы",
  "directCalculation": "Прямой расчет",
  "discount": "Скидка",
  "discountAmount": "Сумма скидки",
  "discountLabel": "Скидка (%)",
  "discountName": "Название скидки",
  "discountPercent": "Процент скидки",
  "discountPsychology": "Психология скидок",
  "discountSize": "Размер скидки",
  "economyLabel": "Экономия",
  "effectiveDiscount": "Эффективная скидка",
  "enterBothPrices": "Введите обе цены",
  "enterPercent": "Введите процент",
  "enterPrice": "Введите цену",
  "enterPriceAndDiscount": "Введите цену и скидку",
  "enterPriceAndSetup": "Введите цену и настройте скидки",
  "example1": "Пример 1",
  "example2": "Пример 2",
  "example3": "Пример 3",
  "exportCascadeDesc": "Экспорт каскадных скидок",
  "exportCascadeTitle": "Каскадные скидки",
  "exportCompareDesc": "Экспорт сравнения",
  "exportCompareTitle": "Сравнение предложений",
  "exportReverseDesc": "Экспорт обратного расчета",
  "exportReverseTitle": "Обратный расчет",
  "exportSingleDesc": "Экспорт простой скидки",
  "exportSingleTitle": "Простая скидка",
  "faq": { "q1": "Как рассчитать скидку?", "a1": "Скидка = Цена × Процент / 100. Цена со скидкой = Цена - Скидка.", "q2": "Что такое каскадные скидки?", "a2": "Последовательное применение нескольких скидок, каждая к уже уменьшенной цене.", "q3": "Как сравнить предложения?", "a3": "Введите все варианты и сравните финальные цены.", "q4": "Почему 10%+10% не равно 20%?", "a4": "При каскаде вторая скидка применяется к уже уменьшенной цене.", "q5": "Когда лучшие скидки?", "a5": "Черная пятница, после Нового года, конец сезона." },
  "fillOptionsForComparison": "Заполните варианты для сравнения",
  "finalPrice": "Финальная цена",
  "finalPriceWithDiscount": "Цена со скидкой",
  "firstDiscount": "Первая скидка",
  "firstDiscountLabel": "Скидка 1 (%)",
  "formula1": "Скидка = Цена × %/100",
  "formula2": "Цена со скидкой = Цена - Скидка",
  "formula3": "% = (Старая - Новая) / Старая × 100",
  "fourthDiscountLabel": "Скидка 4 (%)",
  "gardenGoods": "Садовые товары",
  "heading": "Калькулятор скидок",
  "hiddenConditionsTip": "Скрытые условия",
  "hiddenTipDesc": "Читайте мелкий шрифт",
  "holidayGoods": "Праздничные товары",
  "id": "ID",
  "initialData": "Исходные данные",
  "januaryFebruary": "Январь-Февраль",
  "juneAugust": "Июнь-Август",
  "marchMay": "Март-Май",
  "marketingTricks": "Маркетинговые уловки",
  "maximizeSavings": "Максимизация экономии",
  "maximumSavings": "Максимальная экономия",
  "optionN": "Вариант",
  "optionsToCompare": "Варианты для сравнения",
  "originalPrice": "Исходная цена",
  "paretoDesc": "80% экономии дают 20% скидок",
  "paretoLaw": "Закон Парето",
  "percent": "Процент",
  "practicalTips": "Практические советы",
  "preNewYearDiscounts": "Предновогодние скидки",
  "price": "Цена",
  "priceAfterDiscount": "Цена после скидки",
  "priceBeforeAllDiscounts": "Цена до всех скидок",
  "priceBeforeDiscount": "Цена до скидки",
  "priceBeforeDiscountShort": "До скидки",
  "priceWithDiscount": "Цена со скидкой",
  "priceWithDiscountLabel": "Цена со скидкой",
  "priceWithoutDiscount": "Цена без скидки",
  "productPrice": "Цена товара",
  "rational1": "Сравнивайте цены в разных магазинах",
  "rational2": "Проверяйте историю цен",
  "rational3": "Не покупайте ненужное только из-за скидки",
  "rational4": "Рассчитывайте реальную экономию",
  "rationalApproach": "Рациональный подход",
  "remove": "Удалить",
  "result": "Результат",
  "resultLabel": "Результат",
  "reverseCalculation": "Обратный расчет",
  "reverseCalculationFormula": "Расчет процента скидки",
  "reverseDescription": "Узнать процент скидки по двум ценам",
  "reverseExample": "Пример обратного расчета",
  "savings": "Экономия",
  "savingsTips": "Советы по экономии",
  "schoolOfficeGoods": "Школьные и офисные товары",
  "seasonalCalendar": "Сезонный календарь скидок",
  "secondDiscount": "Вторая скидка",
  "secondDiscountLabel": "Скидка 2 (%)",
  "septemberDecember": "Сентябрь-Декабрь",
  "singleDescription": "Расчет одной скидки",
  "singleDiscount": "Простая скидка",
  "singleExample": "Пример простой скидки",
  "sportsGoods": "Спортивные товары",
  "springDiscounts": "Весенние распродажи",
  "summerSales": "Летние распродажи",
  "thirdDiscountLabel": "Скидка 3 (%)",
  "tip1": "Всегда сравнивайте финальные цены",
  "tip2": "Проверяйте цену до скидки",
  "tip3": "Учитывайте скрытые условия",
  "tip4": "Планируйте покупки заранее",
  "totalSavings": "Общая экономия",
  "touristGoods": "Туристические товары",
  "trick1": "Завышенная начальная цена",
  "trick2": "Скидка от завышенной цены",
  "trick3": "Ограниченное время акции",
  "trick4": "Мелкий шрифт в условиях",
  "validationDiscountNegative": "Скидка не может быть отрицательной",
  "validationDiscountOver100": "Скидка не может превышать 100%",
  "validationEnterCorrectPercent": "Введите корректный процент",
  "validationEnterCorrectPrice": "Введите корректную цену",
  "validationPriceAboveZero": "Цена должна быть больше нуля",
  "validationPriceTooLarge": "Цена слишком большая",
  "watch1": "Сравнение с конкурентами",
  "watch2": "История цены товара",
  "watch3": "Срок действия скидки",
  "watch4": "Условия возврата",
  "whatToWatch": "На что обращать внимание",
  "winterClothes": "Зимняя одежда"
};

const discountKk = {
  "subtitle": "Жеңілдіктерді есептеу және ұсыныстарды салыстыру",
  "addDiscount": "Жеңілдік қосу",
  "addOption": "Нұсқа қосу",
  "additionalDiscountLabel": "Қос. жеңілдік (%)",
  "afterHolidaySales": "Мерекелерден кейінгі сатылымдар",
  "appliedDiscounts": "Қолданылған жеңілдіктер",
  "applyingSteps": "Қолдану тәртібі",
  "bestOption": "Ең жақсы нұсқа",
  "blackFriday": "Қара жұма",
  "calculation": "Есептеу",
  "calculationExamples": "Есептеу мысалдары",
  "calculationFormulas": "Есептеу формулалары",
  "calculationResult": "Есептеу нәтижесі",
  "calculationType": "Есептеу түрі",
  "cascadeDescription": "Бірнеше жеңілдікті кезекпен қолдану",
  "cascadeDiscounts": "Каскадты жеңілдіктер",
  "cascadeDiscountsTip": "Каскадты жеңілдіктер кезекпен қолданылады",
  "cascadeExample": "Каскадты жеңілдіктер мысалы",
  "cascadeFeatures": "Каскадты жеңілдіктер ерекшеліктері",
  "cascadeFeaturesDesc": "Әр келесі жеңілдік азайтылған бағаға қолданылады",
  "cascadeResult": "Каскадты жеңілдіктер нәтижесі",
  "cascadeTipDesc": "Жалпы жеңілдік жекелегендердің сомасынан аз",
  "compareDescription": "Бірнеше ұсынысты салыстыру",
  "compareDiscounts": "Жеңілдіктерді салыстыру",
  "compareExample": "Салыстыру мысалы",
  "compareOffersTip": "Соңғы бағаларды салыстырыңыз",
  "compareTipDesc": "Үлкен жеңілдік әрқашан тиімді емес",
  "comparisonResults": "Салыстыру нәтижелері",
  "coolingDevices": "Кондиционерлер мен желдеткіштер",
  "directCalculation": "Тікелей есептеу",
  "discount": "Жеңілдік",
  "discountAmount": "Жеңілдік сомасы",
  "discountLabel": "Жеңілдік (%)",
  "discountName": "Жеңілдік атауы",
  "discountPercent": "Жеңілдік пайызы",
  "discountPsychology": "Жеңілдіктер психологиясы",
  "discountSize": "Жеңілдік мөлшері",
  "economyLabel": "Үнемдеу",
  "effectiveDiscount": "Тиімді жеңілдік",
  "enterBothPrices": "Екі бағаны да енгізіңіз",
  "enterPercent": "Пайызды енгізіңіз",
  "enterPrice": "Бағаны енгізіңіз",
  "enterPriceAndDiscount": "Бағаны және жеңілдікті енгізіңіз",
  "enterPriceAndSetup": "Бағаны енгізіп, жеңілдіктерді баптаңыз",
  "example1": "Мысал 1",
  "example2": "Мысал 2",
  "example3": "Мысал 3",
  "faq": { "q1": "Жеңілдікті қалай есептеу керек?", "a1": "Жеңілдік = Баға × Пайыз / 100. Жеңілдікті баға = Баға - Жеңілдік.", "q2": "Каскадты жеңілдіктер дегеніміз не?", "a2": "Бірнеше жеңілдікті кезекпен қолдану, әрқайсысы азайтылған бағаға.", "q3": "Ұсыныстарды қалай салыстыруға болады?", "a3": "Барлық нұсқаларды енгізіп, соңғы бағаларды салыстырыңыз.", "q4": "Неге 10%+10% 20%-ға тең емес?", "a4": "Каскадта екінші жеңілдік азайтылған бағаға қолданылады.", "q5": "Ең жақсы жеңілдіктер қашан?", "a5": "Қара жұма, Жаңа жылдан кейін, маусым соңы." },
  "fillOptionsForComparison": "Салыстыру үшін нұсқаларды толтырыңыз",
  "finalPrice": "Соңғы баға",
  "finalPriceWithDiscount": "Жеңілдікті баға",
  "firstDiscount": "Бірінші жеңілдік",
  "firstDiscountLabel": "Жеңілдік 1 (%)",
  "formula1": "Жеңілдік = Баға × %/100",
  "formula2": "Жеңілдікті баға = Баға - Жеңілдік",
  "formula3": "% = (Ескі - Жаңа) / Ескі × 100",
  "heading": "Жеңілдіктер калькуляторы",
  "maximumSavings": "Максималды үнемдеу",
  "optionN": "Нұсқа",
  "optionsToCompare": "Салыстыруға арналған нұсқалар",
  "originalPrice": "Бастапқы баға",
  "practicalTips": "Практикалық кеңестер",
  "price": "Баға",
  "priceAfterDiscount": "Жеңілдіктен кейінгі баға",
  "priceBeforeDiscount": "Жеңілдікке дейінгі баға",
  "priceWithDiscount": "Жеңілдікті баға",
  "result": "Нәтиже",
  "reverseCalculation": "Кері есептеу",
  "savings": "Үнемдеу",
  "singleDiscount": "Қарапайым жеңілдік",
  "totalSavings": "Жалпы үнемдеу"
};

// Apply
if (ruJson['discount']) Object.assign(ruJson['discount'], discountRu);
if (!kkJson['discount']) kkJson['discount'] = { title: "Жеңілдіктер калькуляторы", description: "Жеңілдіктерді есептеу" };
Object.assign(kkJson['discount'], discountKk);

fs.writeFileSync(ruPath, JSON.stringify(ruJson, null, 2), 'utf-8');
fs.writeFileSync(kkPath, JSON.stringify(kkJson, null, 2), 'utf-8');
console.log('✅ Discount translations added!');


